-- =====================================================
-- V1__init.sql
-- Migração inicial - Criação da estrutura do banco
-- Banco: PostgreSQL
-- Projeto: Sistema de Agendamento
-- =====================================================

-- =====================================================
-- Tabela: admin_users
-- Responsável por armazenar usuários administradores
-- =====================================================
CREATE TABLE public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID único
  enabled BOOLEAN NOT NULL,                              -- Usuário ativo/inativo
  password_hash VARCHAR(255) NOT NULL,                   -- Senha criptografada
  username VARCHAR(255) NOT NULL                         -- Nome de login
);

-- Garante que não existam usuários com o mesmo login
ALTER TABLE public.admin_users
  ADD CONSTRAINT uk_admin_users_username UNIQUE (username);


-- =====================================================
-- Tabela: agendamentos
-- Armazena os agendamentos realizados pelos clientes
-- =====================================================
CREATE TABLE public.agendamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID do agendamento
  cliente VARCHAR(255) NOT NULL,                          -- Nome do cliente
  data_hora TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,       -- Data e hora marcada
  servico_id BIGINT NOT NULL,                              -- ID do serviço
  servico_nome VARCHAR(255) NOT NULL,                      -- Nome do serviço
  valor NUMERIC(10,2) NOT NULL                             -- Valor cobrado
);


-- =====================================================
-- Tabela: dia_bloqueado
-- Guarda datas em que não haverá atendimento
-- =====================================================
CREATE TABLE public.dia_bloqueado (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID
  data DATE NOT NULL                                     -- Data bloqueada
);

-- Impede duplicação de dias bloqueados
ALTER TABLE public.dia_bloqueado
  ADD CONSTRAINT uk_dia_bloqueado_data UNIQUE (data);


-- =====================================================
-- Tabela: funcionamento_config
-- Configura horários e dias de funcionamento
-- =====================================================
CREATE TABLE public.funcionamento_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID da configuração

  seg BOOLEAN NOT NULL, -- Segunda-feira ativa
  ter BOOLEAN NOT NULL, -- Terça-feira ativa
  qua BOOLEAN NOT NULL, -- Quarta-feira ativa
  qui BOOLEAN NOT NULL, -- Quinta-feira ativa
  sex BOOLEAN NOT NULL, -- Sexta-feira ativa
  sab BOOLEAN NOT NULL, -- Sábado ativo
  dom BOOLEAN NOT NULL, -- Domingo ativo

  ini_manha VARCHAR(255) NOT NULL, -- Início manhã (ex: 08:00)
  fim_manha VARCHAR(255) NOT NULL, -- Fim manhã   (ex: 12:00)

  ini_tarde VARCHAR(255) NOT NULL, -- Início tarde (ex: 14:00)
  fim_tarde VARCHAR(255) NOT NULL, -- Fim tarde   (ex: 18:00)

  intervalo_min INTEGER NOT NULL   -- Intervalo entre atendimentos (minutos)
);


-- =====================================================
-- Tabela: servicos
-- Armazena os serviços oferecidos pela barbearia
-- =====================================================
CREATE TABLE public.servicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID do serviço
  ativo BOOLEAN NOT NULL,                                -- Serviço ativo/inativo
  nome VARCHAR(255) NOT NULL,                             -- Nome do serviço
  valor NUMERIC(10,2) NOT NULL                            -- Preço
);

-- Evita serviços com nomes repetidos
ALTER TABLE public.servicos
  ADD CONSTRAINT uk_servicos_nome UNIQUE (nome);